/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
   OMSDK is licensed under Mulan PSL v2.
   You can use this software according to the terms and conditions of the Mulan PSL v2.
   You may obtain a copy of Mulan PSL v2 at:
            http://license.coscl.org.cn/MulanPSL2
   THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
   EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
   MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
   See the Mulan PSL v2 for more details.
 */

import errorCode from '@/api/errorCode';

export default {
  // session
  [errorCode.SESSION.ERROR_RESTORE_INIT_WORD_WRONG]: 'errorTip.rootNotChangeDefaultPwdTip',
  [errorCode.SESSION.ERROR_USER_AUTH_FAILED]: 'userInfo.authFailed',
  [errorCode.SESSION.ERROR_ROOT_OPERATE_LOCKED]: 'session.operationLockedTip',
  [errorCode.SESSION.ERROR_SECURITY_CFG_NOT_MEET]: 'session.notMeetRuleTip',
  [errorCode.SESSION.ERROR_USER_NOT_MATCH_PASSWORD]: 'userInfo.userNotMatchPassword',
  [errorCode.SESSION.ERROR_DUPLICATE_PASSWORD]: 'userInfo.duplicatePassword',
  [errorCode.SESSION.ERROR_PASSWORD_IS_DEFAULT]: 'userInfo.defaultPassword',
  [errorCode.SESSION.ERROR_PASSWORD_IS_WEAK]: 'userInfo.weakPassword',
  [errorCode.SESSION.ERROR_PASSWORD_REVERSAL]: 'userInfo.reversalPassword',
  [errorCode.SESSION.ERROR_USERNAME_USED]: 'userInfo.accountUsed',
  [errorCode.SESSION.ERROR_OS_USER_NOT_EXIST]: 'userInfo.accountNotExist',
  [errorCode.SESSION.ERROR_INTERNAL]: 'errorTip.internalError',
  [errorCode.SESSION.ERROR_TIME_LIMIT_EXCEEDED]: 'errorTip.timeLimitExceeded',
  [errorCode.SESSION.ERROR_USER_NOT_FOUND]: 'errorTip.userNotFound',
  [errorCode.SESSION.ERROR_SESSION_NOT_FOUND]: 'errorTip.sessionNotFoundTip',
  [errorCode.SESSION.ERROR_DB_OPERATION_FAILED]: 'errorTip.dbOperationFailedTip',
  [errorCode.SESSION.ERROR_PARAM_RANGE]: 'errorTip.argRangeInvalidTip',
  [errorCode.SESSION.ERROR_USERNAME_OS_MODIFY]: 'errorTip.modifyOsUsernameFailedTip',
  [errorCode.SESSION.ERROR_PASSWORD_OS_MODIFY]: 'errorTip.modifyOsPasswdFailedTip',
  [errorCode.SESSION.ERROR_PASSWORD_TWO_INCONSISTENT]: 'errorTip.twoPasswdInconsistentTip',
  [errorCode.SESSION.ERROR_EDGE_CONFIG_NOT_FOUND]: 'errorTip.configNotFoundTip',
  [errorCode.SESSION.ERROR_SERVICE_IS_STARTING]: 'errorTip.serviceIsRunning',
  [errorCode.SESSION.ERROR_SERVICE_STARTUP_FAILED]: 'errorTip.serviceStartupFailed',
  // common
  [errorCode.COMMON.ERROR_INVALID_PARAMS]: 'errorTip.invalidParamsErrorTip',
  [errorCode.COMMON.ERROR_OPERATE_IS_BUSY]: 'errorTip.operationBusyTip',
  [errorCode.COMMON.ERROR_ARGUMENT_EMPTY]: 'errorTip.invalidParamsErrorTip',
  [errorCode.COMMON.ERROR_CMD_EXEC_ERROR]: 'errorTip.cmdExecErrorTip',
  [errorCode.COMMON.ERROR_FILE_OPEN]: 'errorTip.openFileErrorTip',
  [errorCode.COMMON.ERROR_OPERATION_ILLEGAL]: 'errorTip.illegalOperationTip',
  [errorCode.COMMON.ERROR_ARGUMENT_NOT_EXIST]: 'errorTip.argumentNotExistTip',
  [errorCode.COMMON.ERROR_RESTORE_DEFAULTS]: 'errorTip.restoreFailedTip',
  [errorCode.COMMON.ERROR_DIR_SPACE_LOW]: 'errorTip.spaceIsLowTip',
  [errorCode.COMMON.ERROR_FILE_PATH_FORMAT]: 'errorTip.filePathErrorTip',
  [errorCode.COMMON.ERROR_FILE_PATH_NULL]: 'errorTip.filePathNullTip',
  [errorCode.COMMON.ERROR_FILE_PATH_LONG]: 'errorTip.filePathLongTip',
  [errorCode.COMMON.ERROR_FILE_PATH_SIZE]: 'errorTip.filePathSizeErrorTip',
  [errorCode.COMMON.ERROR_ARGUMENT_FORMAT]: 'errorTip.argFormatErrorTip',
  [errorCode.COMMON.ERROR_FILE_PATH_NOT_EXIST]: 'errorTip.filePathNotExistTip',
  [errorCode.COMMON.ERROR_RETURN_VALUE]: 'errorTip.returnEmptyTip',
  [errorCode.COMMON.ERROR_COLLECTION_LENGTH]: 'errorTip.collectionEmptyTip',
  [errorCode.COMMON.ERROR_ARGUMENT_TYPE]: 'errorTip.argInvalidTip',
  [errorCode.COMMON.ERROR_INTERNAL_SERVER]: 'errorTip.InternalErrorTip',
  [errorCode.COMMON.ERROR_ARGUMENT_NUMBER_WRONG]: 'errorTip.argNumberErrorTip',
  [errorCode.COMMON.ERROR_REQUEST_ARGUMENT_JSON]: 'errorTip.requestMsgShouldJsonTip',
  [errorCode.COMMON.ERROR_ARGUMENT_VALUE_WRONG]: 'errorTip.argValueInvalidTip',
  [errorCode.COMMON.ERROR_PARAM_RANGE_WRONG]: 'errorTip.argRangeInvalidTip',
  [errorCode.COMMON.ERROR_MODIFY_FAILED]: 'errorTip.modifyFailedTip',
  [errorCode.COMMON.ERROR_FILE_PATH_SOFT_LINK]: 'errorTip.filePathSoftlinkTip',
  [errorCode.COMMON.ERROR_FILE_PATH_CHECK]: 'errorTip.filePathCheckFailedTip',
  [errorCode.COMMON.ERROR_RECOVER_OS]: 'errorTip.recoverMiniOs',
  // upload
  [errorCode.UPLOAD.ERROR_EMPTY_FILE]: 'errorTip.emptyFile',
  [errorCode.UPLOAD.ERROR_SPACE_INSUFFICIENT]: 'errorTip.spaceInsufficientTip',
  [errorCode.UPLOAD.ERROR_FILE_SIZE_TOO_LARGE]: 'errorTip.fileTooLargeTip',
  [errorCode.UPLOAD.ERROR_FILE_NOT_EXIST]: 'errorTip.noFileTip',
  [errorCode.UPLOAD.ERROR_UPLOAD_FLAG]: 'common.forbiddenUploadOrWaitTip',
  // NIC
  [errorCode.NIC.ERROR_TAG_CHECK_FAILED]: 'network.networkWired.checkTagFailedTip',
  [errorCode.NIC.ERROR_DEAL_ETHERNET_INTERFACE_FAILED]: 'network.networkWired.ethFailedTip',
  [errorCode.NIC.ERROR_CONFIG_FILE_NOT_EXIST]: 'network.networkWired.configFileNotExistTip',
  [errorCode.NIC.ERROR_TMP_NETCFG_FILE_INVALID]: 'network.networkWired.netConfigFileCheckFailedTip',
  [errorCode.NIC.ERROR_LOAD_NET_CONFIG_YAML_FAILED]: 'network.networkWired.loadConfigFileFailedTip',
  [errorCode.NIC.ERROR_MODIFY_NETPLAN_FAILED]: 'network.networkWired.modifyConfigFailedTip',
  [errorCode.NIC.ERROR_WRITE_NET_CONFIG_YAML_FAILED]: 'network.networkWired.writeConfigFileFailedTip',
  [errorCode.NIC.ERROR_NETWORK_APPLY_FAILED]: 'network.networkWired.applyFailedTip',
  [errorCode.NIC.ERROR_PING_TEST_FAILED]: 'network.networkWired.pingTestFailedTip',
  [errorCode.NIC.ERROR_WRITE_TAG_FAILED]: 'network.networkWired.writeConfigFileFailedTip',
  [errorCode.NIC.ERROR_WRITE_TAG_LOOK_AFTER_OLD_BER4NIC_FAILED]: 'network.networkWired.writeConfigFileFailedTip',
  [errorCode.NIC.ERROR_SER_NGINX_FAILED]: 'network.networkWired.setNginxFailedTip',
  [errorCode.NIC.ERROR_CREATE_MULTIPLE_IP_FILE_FAILED]: 'network.networkWired.createFileFailedTip',
  [errorCode.NIC.ERROR_WRITE_GATEWAY_FAILED]: 'network.networkWired.setGatewayFailedTip',
  [errorCode.NIC.ERROR_RESTART_NETWORK_FAILED]: 'network.networkWired.restartNetworkFailedTip',
  [errorCode.NIC.ERROR_SOURCE_NOT_EXIST]: 'network.networkWired.sysSrcNotExistTip',
  // NFS
  [errorCode.NFS.ERROR_MOUNT_PATH_EXISTED]: 'disk.nfsManagement.mountPathExistTip',
  [errorCode.NFS.ERROR_MOUNT_PATH_NOT_IN_WHITE_LIST]: 'disk.nfsManagement.mountPathNotInWhiteListTip',
  [errorCode.NFS.ERROR_MOUNT_PATH_SUBDIRECTORY_RELATIONSHIP]: 'disk.nfsManagement.subdirectoryRelationshipTip',
  [errorCode.NFS.ERROR_CONFIGURATION_EXCEEDS_LIMIT]: 'disk.nfsManagement.nfsConfigExceedsLimit',
  [errorCode.NFS.ERROR_MOUNT_FAILED]: 'disk.nfsManagement.mountFailedTip',
  [errorCode.NFS.ERROR_MOUNT_TIME_OUT]: 'disk.nfsManagement.mountTimeoutTip',
  [errorCode.NFS.ERROR_UNMOUNT_PATH_NOT_EXISTED]: 'disk.nfsManagement.unmountPathNotExistTip',
  [errorCode.NFS.ERROR_FILESYSTEM_ERROR]: 'disk.nfsManagement.filesystemErrorTip',
  [errorCode.NFS.ERROR_GET_LOCAL_INFO_FAILED]: 'disk.nfsManagement.getMountInfoFailedTip',
  // serverCert
  [errorCode.CERT.ERROR_CERTIFICATE_INIT_FAILED]: 'certificate.serverCert.initErrorTip',
  [errorCode.CERT.ERROR_CERTIFICATE_OR_PASSWORD_VERIFY_FAILED]: 'certificate.serverCert.checkErrorTip',
  [errorCode.CERT.ERROR_CERTIFICATE_IS_NOT_VALID]: 'certificate.serverCert.validityErrorTip',
  [errorCode.CERT.ERROR_CERTIFICATE_ABOUT_TO_EXPIRE]: 'certificate.serverCert.aboutToExpire',
  [errorCode.CERT.ERROR_CERTIFICATE_TOO_LARGE]: 'certificate.serverCert.isTooLarge',
  [errorCode.CERT.ERROR_CERTIFICATE_HAS_EXPIRED]: 'certificate.serverCert.validityErrorTip',
  [errorCode.CERT.ERROR_CERTIFICATE_DOES_NOT_MATCH]: 'certificate.serverCert.certificateDoesNotMatch',
  [errorCode.CERT.ERROR_CERTIFICATE_WAIT_TIME]: 'certificate.serverCert.forbiddenDownloadOrWaitTip',
  [errorCode.CERT.ERROR_CERTIFICATE_IS_INVALID]: 'certificate.serverCert.certificateIsInvalidTip',
  // drive
  [errorCode.DRIVE.ERROR_PARTITION_NAME]: 'errorTip.partitionNameWrongTip',
  [errorCode.DRIVE.ERROR_PARTITION_IS_SYSTEM_PARTITION]: 'errorTip.sysPartitionTip',
  [errorCode.DRIVE.ERROR_CONVERSE_SITE_PARTITION_FAILED]: 'errorTip.converseSitePartitionFailedTip',
  [errorCode.DRIVE.ERROR_UNMOUNT_FAILED]: 'errorTip.unmountPartitionFailedTip',
  [errorCode.DRIVE.ERROR_DELETE_PARTITION_FAILED]: 'errorTip.deletePartitionFailedTip',
  // journal
  [errorCode.LOG.ERROR_LOG_COLLECT]: 'journal.logCollection.collectError',
  // partition
  [errorCode.PARTITION.ERROR_PARTITION_NAME]: 'disk.localDiskManagement.partitionNameWrongTip',
  [errorCode.PARTITION.ERROR_PARTITION_IS_SYSTEM_PARTITION]: 'disk.localDiskManagement.isSysPartitionTip',
  [errorCode.PARTITION.ERROR_CONVERSE_SITE_PARTITION_FAILED]: 'disk.localDiskManagement.partitionConverseFailedTip',
  [errorCode.PARTITION.ERROR_UNMOUNT_FAILED]: 'disk.localDiskManagement.unmountPartitionFailedTip',
  [errorCode.PARTITION.ERROR_DELETE_PARTITION_FAILED]: 'disk.localDiskManagement.deletePartitionFailedTip',
  [errorCode.PARTITION.ERROR_MOUNT_PATH_NOT_IN_WHITE_LIST]: 'disk.nfsManagement.mountPathNotInWhiteListTip',
  [errorCode.PARTITION.ERROR_DISK_IS_MOUNTED]: 'disk.localDiskManagement.diskHasBeenMountedTip',
  [errorCode.PARTITION.ERROR_MOUNT_PATH_INVALID]: 'disk.localDiskManagement.mountPathInvalidTip',
  [errorCode.PARTITION.ERROR_PATH_MOUNTED]: 'disk.localDiskManagement.pathHasBeenMountedTip',
  [errorCode.PARTITION.ERROR_MOUNT_FAILED]: 'disk.localDiskManagement.mountPartitionFailedTip',
  [errorCode.PARTITION.ERROR_SPACE_NOT_ENOUGH]: 'disk.localDiskManagement.diskSpaceNotEnoughTip',
  [errorCode.PARTITION.ERROR_SYSTEM_BUSY]: 'disk.localDiskManagement.sysBusyTip',
  [errorCode.PARTITION.ERROR_CREATE_PARTITION_FAILED]: 'disk.localDiskManagement.createPartitionFailedTip',
  [errorCode.PARTITION.ERROR_DISK_IS_NOT_MOUNTED]: 'disk.localDiskManagement.diskIsNotMounted',
  [errorCode.PARTITION.ERROR_MOUNT_IS_EXISTED]: 'disk.localDiskManagement.mountPathIsExisted',
  [errorCode.PARTITION.ERROR_DISK_TYPE]: 'disk.localDiskManagement.partitionTypeErrorTip',
  [errorCode.PARTITION.ERROR_DRIVE_LETTER_NOT_EXISTED]: 'disk.localDiskManagement.deviceLetterErrorTip',
  [errorCode.PARTITION.ERROR_PARTITION_NUM]: 'disk.localDiskManagement.exceedLimitErrorTip',
  [errorCode.PARTITION.ERROR_DOCKER_UNMOUNT_FAILED]: 'disk.localDiskManagement.dockerUnmountErrorTip',
  // registration
  [errorCode.REGISTRATION.ERROR_IP_LOCKED]: 'registration.nms.ipLockedTip',
  [errorCode.REGISTRATION.ERROR_CERTIFICATE_FORMAT]: 'registration.nms.wrongCertFormatTip',
  [errorCode.REGISTRATION.ERROR_PUBLIC_KEY]: 'registration.nms.wrongPublicKeyTypeTip',
  [errorCode.REGISTRATION.ERROR_LESS_RSA_PUBLIC_KEY]: 'registration.nms.wrongRSAPublicKeyLengthTip',
  [errorCode.REGISTRATION.ERROR_LESS_EC_PUBLIC_KEY]: 'registration.nms.wrongECPublicKeyLengthTip',
  [errorCode.REGISTRATION.ERROR_SIGNATURE_ALGORITHM]: 'registration.nms.wrongSignatureAlgorithmTip',
  [errorCode.REGISTRATION.ERROR_CERTIFICATE_IS_NOT_CA]: 'registration.nms.wrongNotCATip',
  [errorCode.REGISTRATION.ERROR_CERTIFICATE_KEY_SIGN]: 'registration.nms.wrongNotKeySignTip',
  [errorCode.REGISTRATION.ERROR_CERTIFICATE_CHAIN_NUMS_MAX]: 'registration.nms.wrongNumOfCertChain',
  [errorCode.REGISTRATION.ERROR_CERTIFICATE_CA_SIGNATURE_INVALID]: 'registration.nms.caSignatureInvalid',
  [errorCode.REGISTRATION.ERROR_DOCKER_IS_NOT_MOUNTED]: 'registration.nms.dockerIsNotMounted',
}