/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
   OMSDK is licensed under Mulan PSL v2.
   You can use this software according to the terms and conditions of the Mulan PSL v2.
   You may obtain a copy of Mulan PSL v2 at:
            http://license.coscl.org.cn/MulanPSL2
   THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
   EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
   MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
   See the Mulan PSL v2 for more details.
 */

export default {
  DEFAULT_TIMEOUT: 30 * 1000,
  AUTO_REFRESH: 20 * 1000,
  SESSION_INTERVAL: 30 * 1000,
  MINUTE_TIMEOUT: 60 * 1000,
  MAX_ETH_NUM: 4,
  MIN_ETH_NUM: 1,
  MIN_WEB_TIMEOUT: 5,
  MAX_WEB_TIMEOUT: 120,
  DEFAULT_WEB_TIMEOUT: 15,
  MIN_PASSWORD_VALIDITY: 0,
  MAX_PASSWORD_VALIDITY: 365,
  DEFAULT_PASSWORD_VALIDITY: 90,
  MIN_EXPIRY_ALARM: 7,
  MAX_EXPIRY_ALARM: 180,
  DEFAULT_EXPIRY_ALARM: 10,
  DEFAULT_EMPTY_TEXT: '--',
  CERT_FILE_SIZE: 10 * 1024, // 10KB
  CERT_FILE_SIZE_KB: 10, // 10KB
  FD_CERT_FILE_SIZE_MB: 1, // 1MB
  FD_CRL_FILE_SIZE_KB: 10, // 10KB
  MAX_UPGRADE_FILE_SIZE_BYTE: 512 * 1024 * 1024, // 512MB
  MAX_LOGIN_RULE_FILE_SIZE_KB: 10,
  MAX_LOGIN_RULE_NUM_LIMIT: 30,
  MAX_PENNY_DICT_FILE_SIZE_MB: 20,
}