/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
   OMSDK is licensed under Mulan PSL v2.
   You can use this software according to the terms and conditions of the Mulan PSL v2.
   You may obtain a copy of Mulan PSL v2 at:
            http://license.coscl.org.cn/MulanPSL2
   THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
   EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
   MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
   See the Mulan PSL v2 for more details.
 */

export default {
  'zh': {
    'GMT': {
      'GMT_14': 'GMT-14',
      'GMT_13': 'GMT-13',
      'GMT_12': 'GMT-12',
      'GMT_11': 'GMT-11',
      'GMT_10': 'GMT-10',
      'GMT_9': 'GMT-9',
      'GMT_8': 'GMT-8',
      'GMT_7': 'GMT-7',
      'GMT_6': 'GMT-6',
      'GMT_5': 'GMT-5',
      'GMT_4': 'GMT-4',
      'GMT_3': 'GMT-3',
      'GMT_2': 'GMT-2',
      'GMT_1': 'GMT-1',
      'GMT0': 'GMT',
      'GMT1': 'GMT+1',
      'GMT2': 'GMT+2',
      'GMT3': 'GMT+3',
      'GMT4': 'GMT+4',
      'GMT5': 'GMT+5',
      'GMT6': 'GMT+6',
      'GMT7': 'GMT+7',
      'GMT8': 'GMT+8',
      'GMT9': 'GMT+9',
      'GMT10': 'GMT+10',
      'GMT11': 'GMT+11',
      'GMT12': 'GMT+12',
    },
    'Pacific': {
      'PACIFIC_APIA': '阿皮亚',
      'PACIFIC_AUCKLAND': '奥克兰',
      'PACIFIC_BOUGAINVILLE': '布干维尔岛',
      'PACIFIC_CHATHAM': '查塔姆',
      'PACIFIC_CHUUK': '楚克环礁',
      'PACIFIC_EASTER': '复活岛',
      'PACIFIC_EFATE': '埃法特岛',
      'PACIFIC_ENDERBURY': '恩德伯里岛',
      'PACIFIC_FAKAOFO': '法考福',
      'PACIFIC_FIJI': '斐济',
      'PACIFIC_FUNAFUTI': '富纳富提',
      'PACIFIC_GALAPAGOS': '加拉帕戈斯群岛',
      'PACIFIC_GAMBIER': '甘比尔',
      'PACIFIC_GUADALCANAL': '瓜达尔卡纳尔岛',
      'PACIFIC_GUAM': '关岛',
      'PACIFIC_HONOLULU': '檀香山',
      'PACIFIC_KIRITIMATI': '克里斯马斯',
      'PACIFIC_KOSRAE': '科斯瑞',
      'PACIFIC_KWAJALEIN': '夸贾林岛',
      'PACIFIC_MAJURO': '马朱罗',
      'PACIFIC_MARQUESAS': '马克萨斯',
      'PACIFIC_MIDWAY': '中途岛',
      'PACIFIC_NAURU': '瑙鲁',
      'PACIFIC_NIUE': '纽埃',
      'PACIFIC_NORFOLK': '诺福克',
      'PACIFIC_NOUMEA': '努美阿',
      'PACIFIC_PAGO_PAGO': '帕果帕果',
      'PACIFIC_PALAU': '帕劳群岛',
      'PACIFIC_PITCAIRN': '皮特凯恩群岛',
      'PACIFIC_POHNPEI': '波纳佩',
      'PACIFIC_PORT_MORESBY': '莫尔兹比港',
      'PACIFIC_RAROTONGA': '拉罗汤加岛',
      'PACIFIC_SAIPAN': '塞班岛',
      'PACIFIC_TAHITI': '塔希提岛',
      'PACIFIC_TARAWA': '塔拉瓦',
      'PACIFIC_TONGATAPU': '汤加塔布岛',
      'PACIFIC_WAKE': '威克岛',
      'PACIFIC_WALLIS': '瓦利斯群岛',
    },
    'Indian': {
      'INDIAN_ANTANANARIVO': '安塔那那利佛',
      'INDIAN_CHAGOS': '查戈斯群岛',
      'INDIAN_CHRISTMAS': '圣诞岛',
      'INDIAN_COCOS': '科科斯群岛',
      'INDIAN_COMORO': '科摩罗群岛',
      'INDIAN_KERGUELEN': '凯尔盖朗',
      'INDIAN_MAHE': '马埃岛',
      'INDIAN_MALDIVES': '马尔代夫',
      'INDIAN_MAURITIUS': '毛里求斯',
      'INDIAN_MAYOTTE': '马约特岛',
      'INDIAN_REUNION': '留尼汪岛',
    },
    'Europe': {
      'EUROPE_KIROV': '基洛夫',
      'EUROPE_SATATOV': '萨拉托夫',
      'EUROPE_AMSTERDAM': '阿姆斯特丹',
      'EUROPE_ANDORRA': '安道尔',
      'EUROPE_ASTRAKHAN': '阿斯特拉罕',
      'EUROPE_ATHENS': '雅典',
      'EUROPE_BELGRADE': '贝尔格莱德',
      'EUROPE_BERLIN': '柏林',
      'EUROPE_BRATISLAVA': '伯拉第斯拉瓦',
      'EUROPE_BRUSSELS': '布鲁塞尔',
      'EUROPE_BUCHAREST': '布加勒斯特',
      'EUROPE_BUDAPEST': '布达佩斯',
      'EUROPE_BUSINGEN': '布辛根',
      'EUROPE_CHISINAU': '基希讷乌',
      'EUROPE_COPENHAGEN': '哥本哈根',
      'EUROPE_DUBLIN': '都柏林',
      'EUROPE_GIBRALTAR': '直布罗陀',
      'EUROPE_GUERNSEY': '格恩西岛',
      'EUROPE_HELSINKI': '赫尔辛基',
      'EUROPE_ISLE_OF_MAN': '马恩岛',
      'EUROPE_ISTANBUL': '伊斯坦布尔',
      'EUROPE_JERSEY': '泽西岛',
      'EUROPE_KALININGRAD': '加里宁格勒',
      'EUROPE_KIEV': '基辅',
      'EUROPE_LISBON': '里斯本',
      'EUROPE_LJUBLJANA': '卢布尔雅那',
      'EUROPE_LONDON': '伦敦',
      'EUROPE_LUXEMBOURG': '卢森堡',
      'EUROPE_MADRID': '马德里',
      'EUROPE_MALTA': '马尔他',
      'EUROPE_MARIEHAMN': '玛丽港',
      'EUROPE_MINSK': '明斯克',
      'EUROPE_MONACO': '摩纳哥',
      'EUROPE_MOSCOW': '莫斯科',
      'EUROPE_OSLO': '奥斯陆',
      'EUROPE_PARIS': '巴黎',
      'EUROPE_PODGORICA': '波德戈里察',
      'EUROPE_PRAGUE': '布拉格',
      'EUROPE_RIGA': '里加',
      'EUROPE_ROME': '罗马',
      'EUROPE_SAMARA': '萨马拉',
      'EUROPE_SAN_MARINO': '圣马力诺',
      'EUROPE_SARAJEVO': '萨拉热窝',
      'EUROPE_SIMFEROPOL': '辛菲罗波尔',
      'EUROPE_SKOPJE': '斯科普里',
      'EUROPE_SOFIA': '索非亚',
      'EUROPE_STOCKHOLM': '斯德哥尔摩',
      'EUROPE_TALLINN': '塔林',
      'EUROPE_TIRANE': '地拉那',
      'EUROPE_ULYANOVSK': '乌里扬诺夫斯克',
      'EUROPE_UZHGOROD': '乌日哥罗德',
      'EUROPE_VADUZ': '瓦杜兹',
      'EUROPE_VATICAN': '梵蒂冈',
      'EUROPE_VIENNA': '维也纳',
      'EUROPE_VILNIUS': '维尔纽斯',
      'EUROPE_VOLGOGRAD': '伏尔加格勒',
      'EUROPE_WARSAW': '华沙',
      'EUROPE_ZAGREB': '萨格勒布',
      'EUROPE_ZAPOROZHYE': '扎波罗热',
      'EUROPE_ZURICH': '苏黎世',
    },
    'Australia': {
      'AUSTRALIA_ADELAIDE': '阿德莱德',
      'AUSTRALIA_BRISBANE': '布里斯班',
      'AUSTRALIA_BROKEN_HILL': '布罗肯希尔',
      'AUSTRALIA_CURRIE': '柯里',
      'AUSTRALIA_DARWIN': '达尔文',
      'AUSTRALIA_EUCLA': '尤克拉',
      'AUSTRALIA_HOBART': '霍巴特',
      'AUSTRALIA_LINDEMAN': '林德曼岛',
      'AUSTRALIA_LORD_HOWE': '豪勋爵',
      'AUSTRALIA_MELBOURNE': '墨尔本',
      'AUSTRALIA_PERTH': '珀斯',
      'AUSTRALIA_SYDNEY': '悉尼',
      'AUSTRALIA_VICTORIA': '维多利亚',
    },
    'Atlantic': {
      'ATLANTIC_AZORES': '亚速尔群岛',
      'ATLANTIC_BERMUDA': '百慕大群岛',
      'ATLANTIC_CANARY': '加那利群岛',
      'ATLANTIC_CAPE_VERDE': '佛得角',
      'ATLANTIC_FAROE': '法罗群岛',
      'ATLANTIC_MADEIRA': '马德拉群岛',
      'ATLANTIC_REYKJAVIK': '雷克雅维克',
      'ATLANTIC_SOUTH_GEORGIA': '南乔治亚岛',
      'ATLANTIC_ST_HELENA': '圣赫勒拿岛',
      'ATLANTIC_STANLEY': '斯坦利',
    },
    'Asia': {
      'ASIA_ATYRAU': '阿特劳',
      'ASIA_FAMAGUSTA': '法马古斯塔',
      'ASIA_TOMSK': '托木斯克',
      'ASIA_ADEN': '亚丁',
      'ASIA_ALMATY': '阿拉木图',
      'ASIA_AMMAN': '安曼',
      'ASIA_ANADYR': '阿纳德尔',
      'ASIA_AQTAU': '阿克陶',
      'ASIA_AQTOBE': '阿克托别',
      'ASIA_ASHGABAT': '阿什哈巴特',
      'ASIA_BAGHDAD': '巴格达',
      'ASIA_BAHRAIN': '巴林',
      'ASIA_BAKU': '巴库',
      'ASIA_BANGKOK': '曼谷',
      'ASIA_BARNAUL': '巴尔瑙尔',
      'ASIA_BEIRUT': '贝鲁特',
      'ASIA_BISHKEK': '比什凯克',
      'ASIA_BRUNEI': '文莱',
      'ASIA_CHITA': '赤塔',
      'ASIA_CHOIBALSAN': '乔巴山',
      'ASIA_COLOMBO': '科伦坡',
      'ASIA_DAMASCUS': '大马士革',
      'ASIA_DHAKA': '达卡',
      'ASIA_DILI': '帝力',
      'ASIA_DUBAI': '迪拜',
      'ASIA_DUSHANBE': '杜尚别',
      'ASIA_GAZA': '加沙',
      'ASIA_HEBRON': '希伯伦',
      'ASIA_HO_CHI_MINH': '胡志明市',
      'ASIA_HONG_KONG': '香港',
      'ASIA_HOVD': '科布多',
      'ASIA_IRKUTSK': '伊尔库茨克',
      'ASIA_JAKARTA': '雅加达',
      'ASIA_JAYAPURA': '查亚普拉',
      'ASIA_JERUSALEM': '耶路撒冷',
      'ASIA_KABUL': '喀布尔',
      'ASIA_KAMCHATKA': '堪察加半岛',
      'ASIA_KARACHI': '卡拉奇',
      'ASIA_KATHMANDU': '加德满都',
      'ASIA_KHANDYGA': '汉德加',
      'ASIA_KOLKATA': '加尔各答',
      'ASIA_KRASNOYARSK': '克拉斯诺亚尔斯克',
      'ASIA_KUALA_LUMPUR': '吉隆坡',
      'ASIA_KUCHING': '古晋',
      'ASIA_KUWAIT': '科威特',
      'ASIA_MACAO': '澳门',
      'ASIA_MAGADAN': '马加丹',
      'ASIA_MAKASSAR': '望加锡',
      'ASIA_MANILA': '马尼拉',
      'ASIA_MUSCAT': '马斯喀特',
      'ASIA_NICOSIA': '尼科西亚',
      'ASIA_NOVOKUZNETSK': '新库兹涅茨克',
      'ASIA_NOVOSIBIRSK': '新西伯利亚',
      'ASIA_OMSK': '鄂木斯克',
      'ASIA_ORAL': '乌拉尔',
      'ASIA_PHNOM_PENH': '金边',
      'ASIA_PONTIANAK': '坤甸',
      'ASIA_PYONGYANG': '平壤',
      'ASIA_QATAR': '卡塔尔',
      'ASIA_QYZYLORDA': '克孜勒奥尔达',
      'ASIA_RIYADH': '利雅得',
      'ASIA_SAKHALIN': '库页岛',
      'ASIA_SAMARKAND': '撒马尔罕',
      'ASIA_SEOUL': '首尔',
      'ASIA_SHANGHAI': '上海',
      'ASIA_SINGAPORE': '新加坡',
      'ASIA_SREDNEKOLYMSK': '中科雷姆斯克',
      'ASIA_TAIPEI': '台北',
      'ASIA_TASHKENT': '塔什干',
      'ASIA_TBILISI': '第比利斯',
      'ASIA_TEHRAN': '德黑兰',
      'ASIA_THIMPHU': '廷布',
      'ASIA_TOKYO': '东京',
      'ASIA_ULAANBAATAR': '乌兰巴托',
      'ASIA_URUMQI': '乌鲁木齐',
      'ASIA_USTNERA': '乌斯季内拉',
      'ASIA_VIENTIANE': '万象',
      'ASIA_VLADIVOSTOK': '海参崴',
      'ASIA_YAKUTSK': '雅库茨克',
      'ASIA_YEKATERINBURG': '叶卡捷琳堡',
      'ASIA_YEREVAN': '耶烈万',
    },
    'Arctic': {
      'ARCTIC_LONGYEARBYEN': '朗伊尔城',
    },
    'Antarctica': {
      'ANTARCTICA_CASEY': '东方号站',
      'ANTARCTICA_DAVIS': '戴维斯站',
      'ANTARCTICA_DUMONTDURVILLE': '迪蒙迪维尔南极科考站',
      'ANTARCTICA_MACQUARIE': '麦觉里',
      'ANTARCTICA_MAWSON': '莫森站',
      'ANTARCTICA_MCMURDO': '麦克默多站',
      'ANTARCTICA_PALMER': '帕默',
      'ANTARCTICA_ROTHERA': '罗瑟拉站',
      'ANTARCTICA_SYOWA': '昭和站',
      'ANTARCTICA_TROLL': '特诺尔站',
      'ANTARCTICA_VOSTOK': '沃斯托克',
    },
    'America': {
      'AMERICA_PUNTAARENAS': '蓬塔阿雷纳斯',
      'AMERICA_ADAK': '埃达克',
      'AMERICA_ANCHORAGE': '安克雷奇',
      'AMERICA_ANGUILLA': '安圭拉',
      'AMERICA_ANTIGUA': '安地卡及巴布达',
      'AMERICA_ARAGUAINA': '阿拉瓜伊纳',
      'AMERICA_ARGENTINA_BUENOS_AIRES': '阿根廷/布宜诺斯艾利斯',
      'AMERICA_ARGENTINA_CATAMARCA': '阿根廷/卡塔马卡',
      'AMERICA_ARGENTINA_CORDOBA': '阿根廷/科尔多瓦',
      'AMERICA_ARGENTINA_JUJUY': '阿根廷/胡胡伊',
      'AMERICA_ARGENTINA_LA_RIOJA': '阿根廷/拉里奥哈',
      'AMERICA_ARGENTINA_MENDOZA': '阿根廷/门多萨',
      'AMERICA_ARGENTINA_RIO_GALLEGOS': '阿根廷/奥戈加耶斯',
      'AMERICA_ARGENTINA_SALTA': '阿根廷/萨尔塔',
      'AMERICA_ARGENTINA_SAN_JUAN': '阿根廷/圣胡安',
      'AMERICA_ARGENTINA_SAN_LUIS': '阿根廷/圣路易斯',
      'AMERICA_ARGENTINA_TUCUMAN': '阿根廷/土库曼',
      'AMERICA_ARGENTINA_USHUAIA': '阿根廷/乌斯怀亚',
      'AMERICA_ARUBA': '阿鲁巴',
      'AMERICA_ASUNCION': '亚松森',
      'AMERICA_ATIKOKAN': '阿蒂科肯',
      'AMERICA_BAHIA': '巴伊亚',
      'AMERICA_BAHIA_BANDERAS': '巴伊亚德班德拉斯',
      'AMERICA_BARBADOS': '巴巴多斯',
      'AMERICA_BELEM': '贝伦',
      'AMERICA_BELIZE': '伯利兹城',
      'AMERICA_BLANC_SABLON': '布朗萨布隆',
      'AMERICA_BOA_VISTA': '博阿维塔斯',
      'AMERICA_BOGOTA': '波哥大',
      'AMERICA_BOISE': '博伊西',
      'AMERICA_CAMBRIDGE_BAY': '剑桥湾',
      'AMERICA_CAMPO_GRANDE': '大坎普',
      'AMERICA_CANCUN': '坎昆',
      'AMERICA_CARACAS': '加拉加斯',
      'AMERICA_CAYENNE': '卡宴',
      'AMERICA_CAYMAN': '开曼',
      'AMERICA_CHICAGO': '芝加哥',
      'AMERICA_CHIHUAHUA': '奇瓦瓦',
      'AMERICA_COSTA_RICA': '哥斯达黎加',
      'AMERICA_CRESTON': '克雷斯顿',
      'AMERICA_CUIABA': '库亚巴',
      'AMERICA_CURACAO': '库拉索岛',
      'AMERICA_DANMARKSHAVN': '丹马沙',
      'AMERICA_DAWSON': '道森',
      'AMERICA_DAWSON_CREEK': '道森克里克',
      'AMERICA_DENVER': '丹佛',
      'AMERICA_DETROIT': '底特律',
      'AMERICA_DOMINICA': '多米尼加岛',
      'AMERICA_EDMONTON': '埃德蒙顿',
      'AMERICA_EIRUNEPE': '艾鲁内佩',
      'AMERICA_EL_SALVADOR': '萨尔瓦多',
      'AMERICA_FORT_NELSON': '纳尔逊堡',
      'AMERICA_FORTALEZA': '福塔雷萨',
      'AMERICA_GLACE_BAY': '格莱斯贝',
      'AMERICA_GODTHAB': '戈特霍布',
      'AMERICA_GOOSE_BAY': '鹅湾',
      'AMERICA_GRAND_TURK': '大克斯岛',
      'AMERICA_GRENADA': '格林纳达',
      'AMERICA_GUADELOUPE': '瓜德罗普岛',
      'AMERICA_GUATEMALA': '危地马拉',
      'AMERICA_GUAYAQUIL': '瓜亚基尔',
      'AMERICA_GUYANA': '圭亚那',
      'AMERICA_HALIFAX': '哈里法克斯',
      'AMERICA_HAVANA': '哈瓦那',
      'AMERICA_HERMOSILLO': '埃莫西约',
      'AMERICA_INDIANA_INDIANAPOLIS': '印第安纳州/印第安纳波利斯',
      'AMERICA_INDIANA_KNOX': '印第安纳州/诺克斯',
      'AMERICA_INDIANA_MARENGO': '印第安纳州/马伦戈',
      'AMERICA_INDIANA_PETERSBURG': '印第安纳州/彼得斯堡',
      'AMERICA_INDIANA_TELL_CITY': '印第安纳州/退尔城',
      'AMERICA_INDIANA_VEVAY': '印第安纳州/韦韦',
      'AMERICA_INDIANA_VINCENNES': '印第安纳州/文森斯',
      'AMERICA_INDIANA_WINAMAC': '印第安纳州/威纳马克',
      'AMERICA_INUVIK': '伊努维克',
      'AMERICA_IQALUIT': '伊卡卢伊特',
      'AMERICA_JAMAICA': '牙买加',
      'AMERICA_JUNEAU': '朱诺',
      'AMERICA_KENTUCKY_LOUISVILLE': '肯塔基州/路易斯维尔',
      'AMERICA_KENTUCKY_MONTICELLO': '肯塔基州/蒙蒂塞洛',
      'AMERICA_KRALENDIJK': '卡兰蒂捷克',
      'AMERICA_LA_PAZ': '拉巴斯',
      'AMERICA_LIMA': '利马',
      'AMERICA_LOS_ANGELES': '洛杉矶',
      'AMERICA_LOWER_PRINCES': 'Lower Princes',
      'AMERICA_MACEIO': '马赛约',
      'AMERICA_MANAGUA': '马那瓜',
      'AMERICA_MANAUS': '玛瑙斯',
      'AMERICA_MARIGOT': '马里哥特',
      'AMERICA_MARTINIQUE': '马提尼克',
      'AMERICA_MATAMOROS': '马塔莫罗斯',
      'AMERICA_MAZATLAN': '马萨特兰',
      'AMERICA_MENOMINEE': '梅诺米尼',
      'AMERICA_MERIDA': '梅里达',
      'AMERICA_METLAKATLA': '美特拉卡特拉',
      'AMERICA_MEXICO_CITY': '墨西哥城',
      'AMERICA_MIQUELON': '密克隆岛',
      'AMERICA_MONCTON': '蒙克顿',
      'AMERICA_MONTERREY': '蒙特雷',
      'AMERICA_MONTEVIDEO': '蒙得维的亚',
      'AMERICA_MONTSERRAT': '蒙特色拉特岛',
      'AMERICA_NASSAU': '拿索',
      'AMERICA_NEW_YORK': '纽约',
      'AMERICA_NIPIGON': '尼皮贡',
      'AMERICA_NOME': '诺姆',
      'AMERICA_NORONHA': '诺罗尼亚',
      'AMERICA_NORTH_DAKOTA_BEULAH': '北达科他州/比尤拉',
      'AMERICA_NORTH_DAKOTA_CENTER': '北达科他州/中心',
      'AMERICA_NORTH_DAKOTA_NEW_SALEM': '新赛勒姆',
      'AMERICA_OJINAGA': '奥希纳加',
      'AMERICA_PANAMA': '巴拿马',
      'AMERICA_PANGNIRTUNG': '潘尼尔东',
      'AMERICA_PARAMARIBO': '帕拉马里博',
      'AMERICA_PHOENIX': '凤凰城',
      'AMERICA_PORT_AU_PRINCE': '太子港',
      'AMERICA_PORT_OF_SPAIN': '西班牙港',
      'AMERICA_PORTO_VELHO': '波多韦柳',
      'AMERICA_PUERTO_RICO': '波多黎各',
      'AMERICA_RAINY_RIVER': '雷尼里弗',
      'AMERICA_RANKIN_INLET': '兰金因莱特',
      'AMERICA_RECIFE': '累西腓',
      'AMERICA_REGINA': '里贾纳',
      'AMERICA_RESOLUTE': '雷索卢特',
      'AMERICA_RIO_BRANCO': '里约布兰科',
      'AMERICA_SANTAREM': '圣塔伦',
      'AMERICA_SANTIAGO': '圣地亚哥',
      'AMERICA_SANTO_DOMINGO': '圣多明哥',
      'AMERICA_SAO_PAULO': '圣保罗',
      'AMERICA_SCORESBYSUND': '斯科斯比松',
      'AMERICA_SITKA': '锡特卡',
      'AMERICA_ST_BARTHELEMY': '圣巴泰勒米',
      'AMERICA_ST_JOHNS': '圣约翰市',
      'AMERICA_ST_KITTS': '圣基茨岛',
      'AMERICA_ST_LUCIA': '圣卢西亚',
      'AMERICA_ST_THOMAS': '圣托马斯',
      'AMERICA_ST_VINCENT': '圣文森特',
      'AMERICA_SWIFT_CURRENT': '斯威夫特卡伦特',
      'AMERICA_TEGUCIGALPA': '特古西加尔巴',
      'AMERICA_THULE': '图勒',
      'AMERICA_THUNDER_BAY': '桑德湾',
      'AMERICA_TIJUANA': '提华纳',
      'AMERICA_TORONTO': '多伦多',
      'AMERICA_TORTOLA': '托托拉岛',
      'AMERICA_VANCOUVER': '温哥华',
      'AMERICA_WHITEHORSE': '怀特霍斯',
      'AMERICA_WINNIPEG': '温尼伯',
      'AMERICA_YAKUTAT': '雅库塔特',
      'AMERICA_YELLOWKNIFE': '耶洛奈夫',
    },
    'Africa': {
      'AFRICA_ABIDJAN': '阿比让',
      'AFRICA_ACCRA': '阿克拉',
      'AFRICA_ADDIS_ABABA': '亚的斯亚贝巴',
      'AFRICA_ALGIERS': '阿尔及尔',
      'AFRICA_ASMARA': '阿斯马拉',
      'AFRICA_BAMAKO': '巴马科',
      'AFRICA_BANGUI': '班吉',
      'AFRICA_BANJUL': '班珠尔',
      'AFRICA_BISSAU': '比绍',
      'AFRICA_BLANTYRE': '布兰太尔',
      'AFRICA_BRAZZAVILLE': '布拉柴维尔',
      'AFRICA_BUJUMBURA': '布琼布拉',
      'AFRICA_CAIRO': '开罗',
      'AFRICA_CASABLANCA': '卡萨布兰卡',
      'AFRICA_CEUTA': '休达',
      'AFRICA_CONAKRY': '科纳克里',
      'AFRICA_DAKAR': '达喀尔',
      'AFRICA_DAR_ES_SALAAM': '达累斯萨拉姆',
      'AFRICA_DJIBOUTI': '吉布提',
      'AFRICA_DOUALA': '杜阿拉',
      'AFRICA_FREETOWN': '弗里敦',
      'AFRICA_GABORONE': '哈博罗内',
      'AFRICA_HARARE': '哈拉雷',
      'AFRICA_JOHANNESBURG': '约翰尼斯堡',
      'AFRICA_JUBA': '朱拜尔',
      'AFRICA_KAMPALA': '坎帕拉',
      'AFRICA_KHARTOUM': '喀土穆',
      'AFRICA_KIGALI': '基加利',
      'AFRICA_KINSHASA': '金沙萨',
      'AFRICA_LAGOS': '拉各斯',
      'AFRICA_LIBREVILLE': '利伯维尔',
      'AFRICA_LOME': '洛美',
      'AFRICA_LUANDA': '罗安达',
      'AFRICA_LUBUMBASHI': '卢本巴希',
      'AFRICA_LUSAKA': '卢萨卡',
      'AFRICA_MALABO': '马拉博',
      'AFRICA_MAPUTO': '马普托',
      'AFRICA_MASERU': '马塞鲁',
      'AFRICA_MBABANE': '姆巴巴内',
      'AFRICA_MOGADISHU': '摩加迪休',
      'AFRICA_MONROVIA': '蒙罗维亚',
      'AFRICA_NAIROBI': '内罗比',
      'AFRICA_NDJAMENA': '恩贾梅纳',
      'AFRICA_NIAMEY': '尼亚美',
      'AFRICA_NOUAKCHOTT': '努瓦克肖特',
      'AFRICA_OUAGADOUGOU': '瓦加杜古',
      'AFRICA_PORTO_NOVO': '波尔图',
      'AFRICA_SAO_TOME': '圣多美',
      'AFRICA_TRIPOLI': '的黎波里',
      'AFRICA_TUNIS': '突尼斯',
      'AFRICA_WINDHOEK': '温德和克',
    },
  },
  'en': {
    'GMT': {
      'GMT_14': 'GMT-14',
      'GMT_13': 'GMT-13',
      'GMT_12': 'GMT-12',
      'GMT_11': 'GMT-11',
      'GMT_10': 'GMT-10',
      'GMT_9': 'GMT-9',
      'GMT_8': 'GMT-8',
      'GMT_7': 'GMT-7',
      'GMT_6': 'GMT-6',
      'GMT_5': 'GMT-5',
      'GMT_4': 'GMT-4',
      'GMT_3': 'GMT-3',
      'GMT_2': 'GMT-2',
      'GMT_1': 'GMT-1',
      'GMT0': 'GMT',
      'GMT1': 'GMT+1',
      'GMT2': 'GMT+2',
      'GMT3': 'GMT+3',
      'GMT4': 'GMT+4',
      'GMT5': 'GMT+5',
      'GMT6': 'GMT+6',
      'GMT7': 'GMT+7',
      'GMT8': 'GMT+8',
      'GMT9': 'GMT+9',
      'GMT10': 'GMT+10',
      'GMT11': 'GMT+11',
      'GMT12': 'GMT+12',
    },
    'Pacific': {
      'PACIFIC_APIA': 'Apia',
      'PACIFIC_AUCKLAND': 'Auckland',
      'PACIFIC_BOUGAINVILLE': 'Bougainville',
      'PACIFIC_CHATHAM': 'Chatham',
      'PACIFIC_CHUUK': 'Chuuk',
      'PACIFIC_EASTER': 'Easter',
      'PACIFIC_EFATE': 'Efate',
      'PACIFIC_ENDERBURY': 'Enderbury',
      'PACIFIC_FAKAOFO': 'Fakaofo',
      'PACIFIC_FIJI': 'Fiji',
      'PACIFIC_FUNAFUTI': 'Funafuti',
      'PACIFIC_GALAPAGOS': 'Galapagos',
      'PACIFIC_GAMBIER': 'Gambier',
      'PACIFIC_GUADALCANAL': 'Guadalcanal',
      'PACIFIC_GUAM': 'Guam',
      'PACIFIC_HONOLULU': 'Honolulu',
      'PACIFIC_KIRITIMATI': 'Kiritimati',
      'PACIFIC_KOSRAE': 'Kosrae',
      'PACIFIC_KWAJALEIN': 'Kwajalein',
      'PACIFIC_MAJURO': 'Majuro',
      'PACIFIC_MARQUESAS': 'Marquesas',
      'PACIFIC_MIDWAY': 'Midway',
      'PACIFIC_NAURU': 'Nauru',
      'PACIFIC_NIUE': 'Niue',
      'PACIFIC_NORFOLK': 'Norfolk',
      'PACIFIC_NOUMEA': 'Noumea',
      'PACIFIC_PAGO_PAGO': 'Pago Pago',
      'PACIFIC_PALAU': 'Palau',
      'PACIFIC_PITCAIRN': 'Pitcairn',
      'PACIFIC_POHNPEI': 'Pohnpei',
      'PACIFIC_PORT_MORESBY': 'Port Moresby',
      'PACIFIC_RAROTONGA': 'Rarotonga',
      'PACIFIC_SAIPAN': 'Saipan',
      'PACIFIC_TAHITI': 'Tahiti',
      'PACIFIC_TARAWA': 'Tarawa',
      'PACIFIC_TONGATAPU': 'Tongatapu',
      'PACIFIC_WAKE': 'Wake',
      'PACIFIC_WALLIS': 'Wallis',
    },
    'Indian': {
      'INDIAN_ANTANANARIVO': 'Antananarivo',
      'INDIAN_CHAGOS': 'Chagos',
      'INDIAN_CHRISTMAS': 'Christmas',
      'INDIAN_COCOS': 'Cocos',
      'INDIAN_COMORO': 'Comoro',
      'INDIAN_KERGUELEN': 'Kerguelen',
      'INDIAN_MAHE': 'Mahe',
      'INDIAN_MALDIVES': 'Maldives',
      'INDIAN_MAURITIUS': 'Mauritius',
      'INDIAN_MAYOTTE': 'Mayotte',
      'INDIAN_REUNION': 'Reunion',
    },
    'Europe': {
      'EUROPE_AMSTERDAM': 'Amsterdam',
      'EUROPE_ANDORRA': 'Andorra',
      'EUROPE_ASTRAKHAN': 'Astrakhan',
      'EUROPE_ATHENS': 'Athens',
      'EUROPE_BELGRADE': 'Belgrade',
      'EUROPE_BERLIN': 'Berlin',
      'EUROPE_BRATISLAVA': 'Bratislava',
      'EUROPE_BRUSSELS': 'Brussels',
      'EUROPE_BUCHAREST': 'Bucharest',
      'EUROPE_BUDAPEST': 'Budapest',
      'EUROPE_BUSINGEN': 'Busingen',
      'EUROPE_CHISINAU': 'Chisinau',
      'EUROPE_COPENHAGEN': 'Copenhagen',
      'EUROPE_DUBLIN': 'Dublin',
      'EUROPE_GIBRALTAR': 'Gibraltar',
      'EUROPE_GUERNSEY': 'Guernsey',
      'EUROPE_HELSINKI': 'Helsinki',
      'EUROPE_ISLE_OF_MAN': 'Isle of Man',
      'EUROPE_ISTANBUL': 'Istanbul',
      'EUROPE_JERSEY': 'Jersey',
      'EUROPE_KALININGRAD': 'Kaliningrad',
      'EUROPE_KIEV': 'Kiev',
      'EUROPE_KIROV': 'Kirov',
      'EUROPE_LISBON': 'Lisbon',
      'EUROPE_LJUBLJANA': 'Ljubljana',
      'EUROPE_LONDON': 'London',
      'EUROPE_LUXEMBOURG': 'Luxembourg',
      'EUROPE_MADRID': 'Madrid',
      'EUROPE_MALTA': 'Malta',
      'EUROPE_MARIEHAMN': 'Mariehamn',
      'EUROPE_MINSK': 'Minsk',
      'EUROPE_MONACO': 'Monaco',
      'EUROPE_MOSCOW': 'Moscow',
      'EUROPE_OSLO': 'Oslo',
      'EUROPE_PARIS': 'Paris',
      'EUROPE_PODGORICA': 'Podgorica',
      'EUROPE_PRAGUE': 'Prague',
      'EUROPE_RIGA': 'Riga',
      'EUROPE_ROME': 'Rome',
      'EUROPE_SAMARA': 'Samara',
      'EUROPE_SAN_MARINO': 'San Marino',
      'EUROPE_SARAJEVO': 'Sarajevo',
      'EUROPE_SATATOV': 'Saratov',
      'EUROPE_SIMFEROPOL': 'Simferopol',
      'EUROPE_SKOPJE': 'Skopje',
      'EUROPE_SOFIA': 'Sofia',
      'EUROPE_STOCKHOLM': 'Stockholm',
      'EUROPE_TALLINN': 'Tallinn',
      'EUROPE_TIRANE': 'Tirane',
      'EUROPE_ULYANOVSK': 'Ulyanovsk',
      'EUROPE_UZHGOROD': 'Uzhgorod',
      'EUROPE_VADUZ': 'Vaduz',
      'EUROPE_VATICAN': 'Vatican',
      'EUROPE_VIENNA': 'Vienna',
      'EUROPE_VILNIUS': 'Vilnius',
      'EUROPE_VOLGOGRAD': 'Volgograd',
      'EUROPE_WARSAW': 'Warsaw',
      'EUROPE_ZAGREB': 'Zagreb',
      'EUROPE_ZAPOROZHYE': 'Zaporozhye',
      'EUROPE_ZURICH': 'Zurich',
    },
    'Australia': {
      'AUSTRALIA_ADELAIDE': 'Adelaide',
      'AUSTRALIA_BRISBANE': 'Brisbane',
      'AUSTRALIA_BROKEN_HILL': 'Broken Hill',
      'AUSTRALIA_CURRIE': 'Currie',
      'AUSTRALIA_DARWIN': 'Darwin',
      'AUSTRALIA_EUCLA': 'Eucla',
      'AUSTRALIA_HOBART': 'Hobart',
      'AUSTRALIA_LINDEMAN': 'Lindeman',
      'AUSTRALIA_LORD_HOWE': 'Lord Howe',
      'AUSTRALIA_MELBOURNE': 'Melbourne',
      'AUSTRALIA_PERTH': 'Perth',
      'AUSTRALIA_SYDNEY': 'Sydney',
      'AUSTRALIA_VICTORIA': 'Victoria',
    },
    'Atlantic': {
      'ATLANTIC_AZORES': 'Azores',
      'ATLANTIC_BERMUDA': 'Bermuda',
      'ATLANTIC_CANARY': 'Canary',
      'ATLANTIC_CAPE_VERDE': 'Cape Verde',
      'ATLANTIC_FAROE': 'Faroe',
      'ATLANTIC_MADEIRA': 'Madeira',
      'ATLANTIC_REYKJAVIK': 'Reykjavik',
      'ATLANTIC_SOUTH_GEORGIA': 'South Georgia',
      'ATLANTIC_ST_HELENA': 'St Helena',
      'ATLANTIC_STANLEY': 'Stanley',
    },
    'Asia': {
      'ASIA_ADEN': 'Aden',
      'ASIA_ALMATY': 'Almaty',
      'ASIA_AMMAN': 'Amman',
      'ASIA_ANADYR': 'Anadyr',
      'ASIA_AQTAU': 'Aqtau',
      'ASIA_AQTOBE': 'Aqtobe',
      'ASIA_ASHGABAT': 'Ashgabat',
      'ASIA_ATYRAU': 'Atyrau',
      'ASIA_BAGHDAD': 'Baghdad',
      'ASIA_BAHRAIN': 'Bahrain',
      'ASIA_BAKU': 'Baku',
      'ASIA_BANGKOK': 'Bangkok',
      'ASIA_BARNAUL': 'Barnaul',
      'ASIA_BEIRUT': 'Beirut',
      'ASIA_BISHKEK': 'Bishkek',
      'ASIA_BRUNEI': 'Brunei',
      'ASIA_CHITA': 'Chita',
      'ASIA_CHOIBALSAN': 'Choibalsan',
      'ASIA_COLOMBO': 'Colombo',
      'ASIA_DAMASCUS': 'Damascus',
      'ASIA_DHAKA': 'Dhaka',
      'ASIA_DILI': 'Dili',
      'ASIA_DUBAI': 'Dubai',
      'ASIA_DUSHANBE': 'Dushanbe',
      'ASIA_FAMAGUSTA': 'Famagusta',
      'ASIA_GAZA': 'Gaza',
      'ASIA_HEBRON': 'Hebron',
      'ASIA_HO_CHI_MINH': 'Ho Chi Minh',
      'ASIA_HONG_KONG': 'Hong Kong',
      'ASIA_HOVD': 'Hovd',
      'ASIA_IRKUTSK': 'Irkutsk',
      'ASIA_JAKARTA': 'Jakarta',
      'ASIA_JAYAPURA': 'Jayapura',
      'ASIA_JERUSALEM': 'Jerusalem',
      'ASIA_KABUL': 'Kabul',
      'ASIA_KAMCHATKA': 'Kamchatka',
      'ASIA_KARACHI': 'Karachi',
      'ASIA_KATHMANDU': 'Kathmandu',
      'ASIA_KHANDYGA': 'Khandyga',
      'ASIA_KOLKATA': 'Kolkata',
      'ASIA_KRASNOYARSK': 'Krasnoyarsk',
      'ASIA_KUALA_LUMPUR': 'Kuala Lumpur',
      'ASIA_KUCHING': 'Kuching',
      'ASIA_KUWAIT': 'Kuwait',
      'ASIA_MACAO': 'Macao',
      'ASIA_MAGADAN': 'Magadan',
      'ASIA_MAKASSAR': 'Makassar',
      'ASIA_MANILA': 'Manila',
      'ASIA_MUSCAT': 'Muscat',
      'ASIA_NICOSIA': 'Nicosia',
      'ASIA_NOVOKUZNETSK': 'Novokuznetsk',
      'ASIA_NOVOSIBIRSK': 'Novosibirsk',
      'ASIA_OMSK': 'Omsk',
      'ASIA_ORAL': 'Oral',
      'ASIA_PHNOM_PENH': 'Phnom Penh',
      'ASIA_PONTIANAK': 'Pontianak',
      'ASIA_PYONGYANG': 'Pyongyang',
      'ASIA_QATAR': 'Qatar',
      'ASIA_QYZYLORDA': 'Qyzylorda',
      'ASIA_RIYADH': 'Riyadh',
      'ASIA_SAKHALIN': 'Sakhalin',
      'ASIA_SAMARKAND': 'Samarkand',
      'ASIA_SEOUL': 'Seoul',
      'ASIA_SHANGHAI': 'Shanghai',
      'ASIA_SINGAPORE': 'Singapore',
      'ASIA_SREDNEKOLYMSK': 'Srednekolymsk',
      'ASIA_TAIPEI': 'Taipei',
      'ASIA_TASHKENT': 'Tashkent',
      'ASIA_TBILISI': 'Tbilisi',
      'ASIA_TEHRAN': 'Tehran',
      'ASIA_THIMPHU': 'Thimphu',
      'ASIA_TOKYO': 'Tokyo',
      'ASIA_TOMSK': 'Tmosk',
      'ASIA_ULAANBAATAR': 'Ulaanbaatar',
      'ASIA_URUMQI': 'Urumqi',
      'ASIA_USTNERA': 'Ust-Nera',
      'ASIA_VIENTIANE': 'Vientiane',
      'ASIA_VLADIVOSTOK': 'Vladivostok',
      'ASIA_YAKUTSK': 'Yakutsk',
      'ASIA_YEKATERINBURG': 'Yekaterinburg',
      'ASIA_YEREVAN': 'Yerevan',
    },
    'Arctic': {
      'ARCTIC_LONGYEARBYEN': 'Longyearbyen',
    },
    'Antarctica': {
      'ANTARCTICA_CASEY': 'Casey',
      'ANTARCTICA_DAVIS': 'Davis',
      'ANTARCTICA_DUMONTDURVILLE': 'DumontDUrville',
      'ANTARCTICA_MACQUARIE': 'Macquarie',
      'ANTARCTICA_MAWSON': 'Mawson',
      'ANTARCTICA_MCMURDO': 'McMurdo',
      'ANTARCTICA_PALMER': 'Palmer',
      'ANTARCTICA_ROTHERA': 'Rothera',
      'ANTARCTICA_SYOWA': 'Syowa',
      'ANTARCTICA_TROLL': 'Troll',
      'ANTARCTICA_VOSTOK': 'Vostok',
    },
    'America': {
      'AMERICA_ADAK': 'Adak',
      'AMERICA_ANCHORAGE': 'Anchorage',
      'AMERICA_ANGUILLA': 'Anguilla',
      'AMERICA_ANTIGUA': 'Antigua',
      'AMERICA_ARAGUAINA': 'Araguaina',
      'AMERICA_ARGENTINA_BUENOS_AIRES': 'Argentina/Buenos Aires',
      'AMERICA_ARGENTINA_CATAMARCA': 'Argentina/Catamarca',
      'AMERICA_ARGENTINA_CORDOBA': 'Argentina/Cordoba',
      'AMERICA_ARGENTINA_JUJUY': 'Argentina/Jujuy',
      'AMERICA_ARGENTINA_LA_RIOJA': 'Argentina/La Rioja',
      'AMERICA_ARGENTINA_MENDOZA': 'Argentina/Mendoza',
      'AMERICA_ARGENTINA_RIO_GALLEGOS': 'Argentina/Rio Gallegos',
      'AMERICA_ARGENTINA_SALTA': 'Argentina/Salta',
      'AMERICA_ARGENTINA_SAN_JUAN': 'Argentina/San Juan',
      'AMERICA_ARGENTINA_SAN_LUIS': 'Argentina/San Luis',
      'AMERICA_ARGENTINA_TUCUMAN': 'Argentina/Tucuman',
      'AMERICA_ARGENTINA_USHUAIA': 'Argentina/Ushuaia',
      'AMERICA_ARUBA': 'Aruba',
      'AMERICA_ASUNCION': 'Asuncion',
      'AMERICA_ATIKOKAN': 'Atikokan',
      'AMERICA_BAHIA': 'Bahia',
      'AMERICA_BAHIA_BANDERAS': 'Bahia de Banderas',
      'AMERICA_BARBADOS': 'Barbados',
      'AMERICA_BELEM': 'Belem',
      'AMERICA_BELIZE': 'Belize',
      'AMERICA_BLANC_SABLON': 'Blanc-Sablon',
      'AMERICA_BOA_VISTA': 'Boa Vista',
      'AMERICA_BOGOTA': 'Bogota',
      'AMERICA_BOISE': 'Boise',
      'AMERICA_CAMBRIDGE_BAY': 'Cambridge Bay',
      'AMERICA_CAMPO_GRANDE': 'Campo Grande',
      'AMERICA_CANCUN': 'Cancun',
      'AMERICA_CARACAS': 'Caracas',
      'AMERICA_CAYENNE': 'Cayenne',
      'AMERICA_CAYMAN': 'Cayman',
      'AMERICA_CHICAGO': 'Chicago',
      'AMERICA_CHIHUAHUA': 'Chihuahua',
      'AMERICA_COSTA_RICA': 'Costa Rica',
      'AMERICA_CRESTON': 'Creston',
      'AMERICA_CUIABA': 'Cuiaba',
      'AMERICA_CURACAO': 'Curacao',
      'AMERICA_DANMARKSHAVN': 'Danmarkshavn',
      'AMERICA_DAWSON': 'Dawson',
      'AMERICA_DAWSON_CREEK': 'Dawson Creek',
      'AMERICA_DENVER': 'Denver',
      'AMERICA_DETROIT': 'Detroit',
      'AMERICA_DOMINICA': 'Dominica',
      'AMERICA_EDMONTON': 'Edmonton',
      'AMERICA_EIRUNEPE': 'Eirunepe',
      'AMERICA_EL_SALVADOR': 'El Salvador',
      'AMERICA_FORT_NELSON': 'Fort Nelson',
      'AMERICA_FORTALEZA': 'Fortaleza',
      'AMERICA_GLACE_BAY': 'Glace Bay',
      'AMERICA_GODTHAB': 'Godthab',
      'AMERICA_GOOSE_BAY': 'Goose Bay',
      'AMERICA_GRAND_TURK': 'Grand Turk',
      'AMERICA_GRENADA': 'Grenada',
      'AMERICA_GUADELOUPE': 'Guadeloupe',
      'AMERICA_GUATEMALA': 'Guatemala',
      'AMERICA_GUAYAQUIL': 'Guayaquil',
      'AMERICA_GUYANA': 'Guyana',
      'AMERICA_HALIFAX': 'Halifax',
      'AMERICA_HAVANA': 'Havana',
      'AMERICA_HERMOSILLO': 'Hermosillo',
      'AMERICA_INDIANA_INDIANAPOLIS': 'Indiana/Indianapolis',
      'AMERICA_INDIANA_KNOX': 'Indiana/Knox',
      'AMERICA_INDIANA_MARENGO': 'Indiana/Marengo',
      'AMERICA_INDIANA_PETERSBURG': 'Indiana/Petersburg',
      'AMERICA_INDIANA_TELL_CITY': 'Indiana/Tell City',
      'AMERICA_INDIANA_VEVAY': 'Indiana/Vevay',
      'AMERICA_INDIANA_VINCENNES': 'Indiana/Vincennes',
      'AMERICA_INDIANA_WINAMAC': 'Indiana/Winamac',
      'AMERICA_INUVIK': 'Inuvik',
      'AMERICA_IQALUIT': 'Iqaluit',
      'AMERICA_JAMAICA': 'Jamaica',
      'AMERICA_JUNEAU': 'Juneau',
      'AMERICA_KENTUCKY_LOUISVILLE': 'Kentucky/Louisville',
      'AMERICA_KENTUCKY_MONTICELLO': 'Kentucky/Monticello',
      'AMERICA_KRALENDIJK': 'Kralendijk',
      'AMERICA_LA_PAZ': 'La Paz',
      'AMERICA_LIMA': 'Lima',
      'AMERICA_LOS_ANGELES': 'Los Angeles',
      'AMERICA_LOWER_PRINCES': 'Lower Princes',
      'AMERICA_MACEIO': 'Maceio',
      'AMERICA_MANAGUA': 'Managua',
      'AMERICA_MANAUS': 'Manaus',
      'AMERICA_MARIGOT': 'Marigot',
      'AMERICA_MARTINIQUE': 'Martinique',
      'AMERICA_MATAMOROS': 'Matamoros',
      'AMERICA_MAZATLAN': 'Mazatlan',
      'AMERICA_MENOMINEE': 'Menominee',
      'AMERICA_MERIDA': 'Merida',
      'AMERICA_METLAKATLA': 'Metlakatla',
      'AMERICA_MEXICO_CITY': 'Mexico City',
      'AMERICA_MIQUELON': 'Miquelon',
      'AMERICA_MONCTON': 'Moncton',
      'AMERICA_MONTERREY': 'Monterrey',
      'AMERICA_MONTEVIDEO': 'Montevideo',
      'AMERICA_MONTSERRAT': 'Montserrat',
      'AMERICA_NASSAU': 'Nassau',
      'AMERICA_NEW_YORK': 'New York',
      'AMERICA_NIPIGON': 'Nipigon',
      'AMERICA_NOME': 'Nome',
      'AMERICA_NORONHA': 'Noronha',
      'AMERICA_NORTH_DAKOTA_BEULAH': 'North Dakota/Beulah',
      'AMERICA_NORTH_DAKOTA_CENTER': 'North Dakota/Center',
      'AMERICA_NORTH_DAKOTA_NEW_SALEM': 'North Dakota/New Salem',
      'AMERICA_OJINAGA': 'Ojinaga',
      'AMERICA_PANAMA': 'Panama',
      'AMERICA_PANGNIRTUNG': 'Pangnirtung',
      'AMERICA_PARAMARIBO': 'Paramaribo',
      'AMERICA_PHOENIX': 'Phoenix',
      'AMERICA_PORT_AU_PRINCE': 'Port-au-Prince',
      'AMERICA_PORT_OF_SPAIN': 'Port of Spain',
      'AMERICA_PORTO_VELHO': 'Porto Velho',
      'AMERICA_PUERTO_RICO': 'Puerto Rico',
      'AMERICA_PUNTAARENAS': 'Punta Arenas',
      'AMERICA_RAINY_RIVER': 'Rainy River',
      'AMERICA_RANKIN_INLET': 'Rankin Inlet',
      'AMERICA_RECIFE': 'Recife',
      'AMERICA_REGINA': 'Regina',
      'AMERICA_RESOLUTE': 'Resolute',
      'AMERICA_RIO_BRANCO': 'Rio Branco',
      'AMERICA_SANTAREM': 'Santarem',
      'AMERICA_SANTIAGO': 'Santiago',
      'AMERICA_SANTO_DOMINGO': 'Santo Domingo',
      'AMERICA_SAO_PAULO': 'Sao Paulo',
      'AMERICA_SCORESBYSUND': 'Scoresbysund',
      'AMERICA_SITKA': 'Sitka',
      'AMERICA_ST_BARTHELEMY': 'St Barthelemy',
      'AMERICA_ST_JOHNS': 'St Johns',
      'AMERICA_ST_KITTS': 'St Kitts',
      'AMERICA_ST_LUCIA': 'St Lucia',
      'AMERICA_ST_THOMAS': 'St Thomas',
      'AMERICA_ST_VINCENT': 'St Vincent',
      'AMERICA_SWIFT_CURRENT': 'Swift Current',
      'AMERICA_TEGUCIGALPA': 'Tegucigalpa',
      'AMERICA_THULE': 'Thule',
      'AMERICA_THUNDER_BAY': 'Thunder Bay',
      'AMERICA_TIJUANA': 'Tijuana',
      'AMERICA_TORONTO': 'Toronto',
      'AMERICA_TORTOLA': 'Tortola',
      'AMERICA_VANCOUVER': 'Vancouver',
      'AMERICA_WHITEHORSE': 'Whitehorse',
      'AMERICA_WINNIPEG': 'Winnipeg',
      'AMERICA_YAKUTAT': 'Yakutat',
      'AMERICA_YELLOWKNIFE': 'Yellowknife',
    },
    'Africa': {
      'AFRICA_ABIDJAN': 'Abidjan',
      'AFRICA_ACCRA': 'Accra',
      'AFRICA_ADDIS_ABABA': 'Addis Ababa',
      'AFRICA_ALGIERS': 'Algiers',
      'AFRICA_ASMARA': 'Asmara',
      'AFRICA_BAMAKO': 'Bamako',
      'AFRICA_BANGUI': 'Bangui',
      'AFRICA_BANJUL': 'Banjul',
      'AFRICA_BISSAU': 'Bissau',
      'AFRICA_BLANTYRE': 'Blantyre',
      'AFRICA_BRAZZAVILLE': 'Brazzaville',
      'AFRICA_BUJUMBURA': 'Bujumbura',
      'AFRICA_CAIRO': 'Cairo',
      'AFRICA_CASABLANCA': 'Casablanca',
      'AFRICA_CEUTA': 'Ceuta',
      'AFRICA_CONAKRY': 'Conakry',
      'AFRICA_DAKAR': 'Dakar',
      'AFRICA_DAR_ES_SALAAM': 'Dar es Salaam',
      'AFRICA_DJIBOUTI': 'Djibouti',
      'AFRICA_DOUALA': 'Douala',
      'AFRICA_FREETOWN': 'Freetown',
      'AFRICA_GABORONE': 'Gaborone',
      'AFRICA_HARARE': 'Harare',
      'AFRICA_JOHANNESBURG': 'Johannesburg',
      'AFRICA_JUBA': 'Juba',
      'AFRICA_KAMPALA': 'Kampala',
      'AFRICA_KHARTOUM': 'Khartoum',
      'AFRICA_KIGALI': 'Kigali',
      'AFRICA_KINSHASA': 'Kinshasa',
      'AFRICA_LAGOS': 'Lagos',
      'AFRICA_LIBREVILLE': 'Libreville',
      'AFRICA_LOME': 'Lome',
      'AFRICA_LUANDA': 'Luanda',
      'AFRICA_LUBUMBASHI': 'Lubumbashi',
      'AFRICA_LUSAKA': 'Lusaka',
      'AFRICA_MALABO': 'Malabo',
      'AFRICA_MAPUTO': 'Maputo',
      'AFRICA_MASERU': 'Maseru',
      'AFRICA_MBABANE': 'Mbabane',
      'AFRICA_MOGADISHU': 'Mogadishu',
      'AFRICA_MONROVIA': 'Monrovia',
      'AFRICA_NAIROBI': 'Nairobi',
      'AFRICA_NDJAMENA': 'Ndjamena',
      'AFRICA_NIAMEY': 'Niamey',
      'AFRICA_NOUAKCHOTT': 'Nouakchott',
      'AFRICA_OUAGADOUGOU': 'Ouagadougou',
      'AFRICA_PORTO_NOVO': 'Porto-Novo',
      'AFRICA_SAO_TOME': 'Sao Tome',
      'AFRICA_TRIPOLI': 'Tripoli',
      'AFRICA_TUNIS': 'Tunis',
      'AFRICA_WINDHOEK': 'Windhoek',
    },
  },
};