# coding: utf-8
# Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
# OMSDK is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#          http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
import ctypes

MAX_MODULE_NUM = 32
MAX_CFG_FILES = MAX_MODULE_NUM + 1
MAX_DEVICE_NUMBER = 50
MAX_CFG_FILE_SIZE_BYTE = 1 * 1024 * 1024

MAX_STRING_BUFFER_SIZE_BYTE = 512
HEADER_BUFF_SIZE_BYTE = ctypes.sizeof(ctypes.c_int) * 2
MAX_BUFFER_SIZE_BYTE = (MAX_STRING_BUFFER_SIZE_BYTE + HEADER_BUFF_SIZE_BYTE) * 50 + HEADER_BUFF_SIZE_BYTE
MAX_DYNAMIC_MODULE_DEVICE_NAME_LEN = 64
MAX_DYNAMIC_MODULE_DEVICE_NUM = 10
MAX_DYNAMIC_MODULE_DEVICE_BUFFER_SIZE_BYTE = MAX_DYNAMIC_MODULE_DEVICE_NAME_LEN * MAX_DYNAMIC_MODULE_DEVICE_NUM
DYNAMIC_MODULES_POLLING_INTERVAL = 10
FIVE_G_MODULES_POLLING_INTERVAL = 5
